---
name: "Setup Go Workspace"
description: "Configure Go tools with Just"

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.24"
        cache: false

    - name: Install Just
      uses: extractions/setup-just@v2

    - name: Tidy modules
      shell: bash
      run: |
        go mod tidy
